import Phaser from "phaser";

// Four-direction overworld sheets, generated by Meristem from each character's
// documented appearance (jarmstrong158/meristem, tools/vanguard_bestiary.py).
//
// Every other sprite in this game is baked procedurally in sprites.ts, and battle
// sprites stay that way -- they are side-on and never turn. The overworld is the one
// place facing matters, and drawing four views by hand in TypeScript would be four
// times the code to maintain against the same character docs the sheets already read.
//
// Layout: 96x192, 32x48 cells. Columns are idle, walk1, walk2; rows are south, north,
// east, west. Meristem's own walk order is [step, idle, step, idle], which is why the
// cycle below is idle -> walk1 -> idle -> walk2 rather than a straight 0,1,2.
export const OW_CELL_W = 32;
export const OW_CELL_H = 48;
export const OW_DIRS = ["south", "north", "east", "west"] as const;
export type OwDir = (typeof OW_DIRS)[number];

/** Characters with a generated overworld sheet. Anyone absent falls back to their
 *  baked single-view sprite, which is what every NPC still uses. */
export const OW_SHEETS = ["maren", "kael", "lida", "senna", "davan", "yara"] as const;
export type OwChar = (typeof OW_SHEETS)[number];

const key = (who: string) => `ow_${who}`;

/** Queue the sheets. Must run in a scene's `preload`, not `create`: unlike the baked
 *  textures these come off the network. */
export function preloadOverworldSheets(scene: Phaser.Scene) {
  for (const who of OW_SHEETS) {
    if (scene.textures.exists(key(who))) continue;
    scene.load.spritesheet(key(who), `sprites/overworld/${who}_overworld.png`, {
      frameWidth: OW_CELL_W,
      frameHeight: OW_CELL_H,
    });
  }
}

/** Register idle/walk animations per direction. Safe to call from every scene. */
export function registerOverworldAnims(scene: Phaser.Scene) {
  for (const who of OW_SHEETS) {
    if (!scene.textures.exists(key(who))) continue;
    OW_DIRS.forEach((dir, row) => {
      const base = row * 3;
      const idle = `${who}_idle_${dir}`;
      if (!scene.anims.exists(idle)) {
        scene.anims.create({ key: idle, frames: [{ key: key(who), frame: base }], frameRate: 1, repeat: -1 });
      }
      const walk = `${who}_walk_${dir}`;
      if (!scene.anims.exists(walk)) {
        scene.anims.create({
          key: walk,
          frames: [base, base + 1, base, base + 2].map((frame) => ({ key: key(who), frame })),
          frameRate: 8,
          repeat: -1,
        });
      }
    });
  }
}

export function hasOverworldSheet(scene: Phaser.Scene, who: string): who is OwChar {
  return (OW_SHEETS as readonly string[]).includes(who) && scene.textures.exists(key(who));
}

export const overworldTexture = key;

/** Which way a movement vector faces. Horizontal wins ties, so a diagonal reads as
 *  east/west -- the profile carries more information than the front view does. */
export function facingOf(dx: number, dy: number, fallback: OwDir = "south"): OwDir {
  if (dx === 0 && dy === 0) return fallback;
  if (Math.abs(dx) > Math.abs(dy)) return dx > 0 ? "east" : "west";
  return dy > 0 ? "south" : "north";
}

/** Play the right clip for a facing, without restarting an already-running one.
 *  Re-issuing `play` every frame would pin the walk cycle to frame 0 and the
 *  character would slide with its feet planted. */
export function playOverworld(
  sprite: Phaser.GameObjects.Sprite, who: string, dir: OwDir, moving: boolean,
) {
  const want = `${who}_${moving ? "walk" : "idle"}_${dir}`;
  if (sprite.anims.currentAnim?.key !== want) sprite.play(want, true);
}
